// US Electricity Rates by State — auto-generated from Notion
// Source: https://www.notion.so/3377647e6fc54a7fa9e56ecf1ccb954d
// All rates are in $/kWh. Rates represent residential averages.

export interface StateRate {
  state: string;
  stateCode: string;
  region: string;
  standardRate: number;
  offPeakRate: number;
  peakRate: number;
  notes: string;
}

export const stateRates: StateRate[] = [
  {
    state: "Alabama",
    stateCode: "AL",
    region: "South",
    standardRate: 0.155,
    offPeakRate: 0.1,
    peakRate: 0.22,
    notes: "",
  },
  {
    state: "Alaska",
    stateCode: "AK",
    region: "Pacific",
    standardRate: 0.245,
    offPeakRate: 0.18,
    peakRate: 0.31,
    notes: "High rates outside grid-connected areas; varies widely",
  },
  {
    state: "Arizona",
    stateCode: "AZ",
    region: "West",
    standardRate: 0.145,
    offPeakRate: 0.09,
    peakRate: 0.28,
    notes: "APS and SRP have aggressive summer peak rates 3-9pm",
  },
  {
    state: "Arkansas",
    stateCode: "AR",
    region: "South",
    standardRate: 0.118,
    offPeakRate: 0.08,
    peakRate: 0.18,
    notes: "",
  },
  {
    state: "California",
    stateCode: "CA",
    region: "Pacific",
    standardRate: 0.32,
    offPeakRate: 0.25,
    peakRate: 0.55,
    notes: "Highest TOU spreads; PG&E/SCE/SDG&E peak rates among nation's highest",
  },
  {
    state: "Colorado",
    stateCode: "CO",
    region: "West",
    standardRate: 0.145,
    offPeakRate: 0.09,
    peakRate: 0.27,
    notes: "",
  },
  {
    state: "Connecticut",
    stateCode: "CT",
    region: "Northeast",
    standardRate: 0.305,
    offPeakRate: 0.18,
    peakRate: 0.42,
    notes: "",
  },
  {
    state: "Delaware",
    stateCode: "DE",
    region: "Northeast",
    standardRate: 0.155,
    offPeakRate: 0.11,
    peakRate: 0.21,
    notes: "",
  },
  {
    state: "District of Columbia",
    stateCode: "DC",
    region: "Northeast",
    standardRate: 0.158,
    offPeakRate: 0.1,
    peakRate: 0.23,
    notes: "",
  },
  {
    state: "Florida",
    stateCode: "FL",
    region: "South",
    standardRate: 0.146,
    offPeakRate: 0.1,
    peakRate: 0.2,
    notes: "Limited TOU adoption; mostly tiered/flat rates",
  },
  {
    state: "Georgia",
    stateCode: "GA",
    region: "South",
    standardRate: 0.135,
    offPeakRate: 0.08,
    peakRate: 0.22,
    notes: "Georgia Power Plug-in EV plan offers low overnight rates",
  },
  {
    state: "Hawaii",
    stateCode: "HI",
    region: "Pacific",
    standardRate: 0.41,
    offPeakRate: 0.3,
    peakRate: 0.55,
    notes: "Highest standard rates due to imported oil generation",
  },
  {
    state: "Idaho",
    stateCode: "ID",
    region: "West",
    standardRate: 0.105,
    offPeakRate: 0.07,
    peakRate: 0.16,
    notes: "Among lowest in the nation due to hydropower",
  },
  {
    state: "Illinois",
    stateCode: "IL",
    region: "Midwest",
    standardRate: 0.155,
    offPeakRate: 0.09,
    peakRate: 0.24,
    notes: "",
  },
  {
    state: "Indiana",
    stateCode: "IN",
    region: "Midwest",
    standardRate: 0.149,
    offPeakRate: 0.1,
    peakRate: 0.22,
    notes: "",
  },
  {
    state: "Iowa",
    stateCode: "IA",
    region: "Midwest",
    standardRate: 0.132,
    offPeakRate: 0.08,
    peakRate: 0.2,
    notes: "",
  },
  {
    state: "Kansas",
    stateCode: "KS",
    region: "Midwest",
    standardRate: 0.139,
    offPeakRate: 0.09,
    peakRate: 0.21,
    notes: "",
  },
  {
    state: "Kentucky",
    stateCode: "KY",
    region: "South",
    standardRate: 0.124,
    offPeakRate: 0.08,
    peakRate: 0.18,
    notes: "",
  },
  {
    state: "Louisiana",
    stateCode: "LA",
    region: "South",
    standardRate: 0.115,
    offPeakRate: 0.08,
    peakRate: 0.17,
    notes: "",
  },
  {
    state: "Maine",
    stateCode: "ME",
    region: "Northeast",
    standardRate: 0.255,
    offPeakRate: 0.16,
    peakRate: 0.36,
    notes: "",
  },
  {
    state: "Maryland",
    stateCode: "MD",
    region: "Northeast",
    standardRate: 0.165,
    offPeakRate: 0.1,
    peakRate: 0.24,
    notes: "",
  },
  {
    state: "Massachusetts",
    stateCode: "MA",
    region: "Northeast",
    standardRate: 0.3,
    offPeakRate: 0.18,
    peakRate: 0.42,
    notes: "National Grid and Eversource have highest Northeast peaks",
  },
  {
    state: "Michigan",
    stateCode: "MI",
    region: "Midwest",
    standardRate: 0.18,
    offPeakRate: 0.1,
    peakRate: 0.26,
    notes: "",
  },
  {
    state: "Minnesota",
    stateCode: "MN",
    region: "Midwest",
    standardRate: 0.142,
    offPeakRate: 0.08,
    peakRate: 0.22,
    notes: "",
  },
  {
    state: "Mississippi",
    stateCode: "MS",
    region: "South",
    standardRate: 0.135,
    offPeakRate: 0.09,
    peakRate: 0.2,
    notes: "",
  },
  {
    state: "Missouri",
    stateCode: "MO",
    region: "Midwest",
    standardRate: 0.118,
    offPeakRate: 0.07,
    peakRate: 0.21,
    notes: "",
  },
  {
    state: "Montana",
    stateCode: "MT",
    region: "West",
    standardRate: 0.115,
    offPeakRate: 0.08,
    peakRate: 0.17,
    notes: "",
  },
  {
    state: "Nebraska",
    stateCode: "NE",
    region: "Midwest",
    standardRate: 0.114,
    offPeakRate: 0.08,
    peakRate: 0.16,
    notes: "",
  },
  {
    state: "Nevada",
    stateCode: "NV",
    region: "West",
    standardRate: 0.135,
    offPeakRate: 0.08,
    peakRate: 0.3,
    notes: "NV Energy summer peak rates among highest in West",
  },
  {
    state: "New Hampshire",
    stateCode: "NH",
    region: "Northeast",
    standardRate: 0.245,
    offPeakRate: 0.16,
    peakRate: 0.34,
    notes: "",
  },
  {
    state: "New Jersey",
    stateCode: "NJ",
    region: "Northeast",
    standardRate: 0.175,
    offPeakRate: 0.12,
    peakRate: 0.26,
    notes: "",
  },
  {
    state: "New Mexico",
    stateCode: "NM",
    region: "West",
    standardRate: 0.143,
    offPeakRate: 0.08,
    peakRate: 0.24,
    notes: "",
  },
  {
    state: "New York",
    stateCode: "NY",
    region: "Northeast",
    standardRate: 0.235,
    offPeakRate: 0.13,
    peakRate: 0.33,
    notes: "ConEd peak rates very high; upstate NYSEG/RG&E lower",
  },
  {
    state: "North Carolina",
    stateCode: "NC",
    region: "South",
    standardRate: 0.135,
    offPeakRate: 0.09,
    peakRate: 0.21,
    notes: "",
  },
  {
    state: "North Dakota",
    stateCode: "ND",
    region: "Midwest",
    standardRate: 0.106,
    offPeakRate: 0.07,
    peakRate: 0.16,
    notes: "",
  },
  {
    state: "Ohio",
    stateCode: "OH",
    region: "Midwest",
    standardRate: 0.156,
    offPeakRate: 0.1,
    peakRate: 0.22,
    notes: "",
  },
  {
    state: "Oklahoma",
    stateCode: "OK",
    region: "South",
    standardRate: 0.115,
    offPeakRate: 0.07,
    peakRate: 0.19,
    notes: "",
  },
  {
    state: "Oregon",
    stateCode: "OR",
    region: "Pacific",
    standardRate: 0.125,
    offPeakRate: 0.08,
    peakRate: 0.2,
    notes: "",
  },
  {
    state: "Pennsylvania",
    stateCode: "PA",
    region: "Northeast",
    standardRate: 0.175,
    offPeakRate: 0.11,
    peakRate: 0.26,
    notes: "",
  },
  {
    state: "Rhode Island",
    stateCode: "RI",
    region: "Northeast",
    standardRate: 0.295,
    offPeakRate: 0.18,
    peakRate: 0.4,
    notes: "",
  },
  {
    state: "South Carolina",
    stateCode: "SC",
    region: "South",
    standardRate: 0.142,
    offPeakRate: 0.09,
    peakRate: 0.22,
    notes: "",
  },
  {
    state: "South Dakota",
    stateCode: "SD",
    region: "Midwest",
    standardRate: 0.124,
    offPeakRate: 0.08,
    peakRate: 0.18,
    notes: "",
  },
  {
    state: "Tennessee",
    stateCode: "TN",
    region: "South",
    standardRate: 0.122,
    offPeakRate: 0.08,
    peakRate: 0.18,
    notes: "",
  },
  {
    state: "Texas",
    stateCode: "TX",
    region: "South",
    standardRate: 0.149,
    offPeakRate: 0.06,
    peakRate: 0.24,
    notes: "Deregulated market; many free overnight EV plans available",
  },
  {
    state: "Utah",
    stateCode: "UT",
    region: "West",
    standardRate: 0.118,
    offPeakRate: 0.07,
    peakRate: 0.21,
    notes: "",
  },
  {
    state: "Vermont",
    stateCode: "VT",
    region: "Northeast",
    standardRate: 0.205,
    offPeakRate: 0.14,
    peakRate: 0.28,
    notes: "",
  },
  {
    state: "Virginia",
    stateCode: "VA",
    region: "South",
    standardRate: 0.146,
    offPeakRate: 0.1,
    peakRate: 0.22,
    notes: "",
  },
  {
    state: "Washington",
    stateCode: "WA",
    region: "Pacific",
    standardRate: 0.115,
    offPeakRate: 0.08,
    peakRate: 0.16,
    notes: "Low rates from abundant hydropower",
  },
  {
    state: "West Virginia",
    stateCode: "WV",
    region: "South",
    standardRate: 0.145,
    offPeakRate: 0.1,
    peakRate: 0.2,
    notes: "",
  },
  {
    state: "Wisconsin",
    stateCode: "WI",
    region: "Midwest",
    standardRate: 0.176,
    offPeakRate: 0.1,
    peakRate: 0.26,
    notes: "",
  },
  {
    state: "Wyoming",
    stateCode: "WY",
    region: "West",
    standardRate: 0.114,
    offPeakRate: 0.08,
    peakRate: 0.16,
    notes: "",
  },
];

export function getRateByCode(code: string): StateRate | undefined {
  return stateRates.find(r => r.stateCode === code);
}
